package org.example.Model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * JPA entity representing a project in the database.
 * 
 * <p>This entity stores project information including name, description, and XML content
 * generated by OpenAI. It automatically manages creation and update timestamps.</p>
 * 
 * @author AI Project Planner Team
 * @version 1.0
 */
@Entity
@Table(name = "projects")
public class Project {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @Column(nullable = false)
    private String name;
    
    @Column(columnDefinition = "TEXT")
    private String description;
    
    @Column(columnDefinition = "TEXT")
    private String xmlContent;
    
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    /**
     * Automatically sets creation and update timestamps before persisting a new entity.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    /**
     * Automatically updates the update timestamp before updating an existing entity.
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    /**
     * Gets the unique identifier of the project.
     * 
     * @return the project ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the project.
     * 
     * @param id the project ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the name of the project.
     * 
     * @return the project name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the project.
     * 
     * @param name the project name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the description of the project.
     * 
     * @return the project description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the description of the project.
     * 
     * @param description the project description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets the XML content containing the project plan (PRINCE2 and Scrum).
     * 
     * @return the XML content
     */
    public String getXmlContent() {
        return xmlContent;
    }

    /**
     * Sets the XML content containing the project plan.
     * 
     * @param xmlContent the XML content
     */
    public void setXmlContent(String xmlContent) {
        this.xmlContent = xmlContent;
    }

    /**
     * Gets the timestamp when the project was created.
     * 
     * @return the creation timestamp
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the timestamp when the project was created.
     * 
     * @param createdAt the creation timestamp
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Gets the timestamp when the project was last updated.
     * 
     * @return the update timestamp
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Sets the timestamp when the project was last updated.
     * 
     * @param updatedAt the update timestamp
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}

